#!/bin/bash
coin=$1
wallet=$2
worker=$3
thread=$4

if [[ $coin == "scala" ]]
then
  wget https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64.zip && sudo apt install -y unzip && unzip XLArig-v5.2.2-linux-x86_64.zip && ./xlarig -o scala.herominers.com:10131 -u  $wallet -p $worker -k -a panthera -t2 --randomx-1gb-pages
elif [[ $coin == "verus" ]]
then
  wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz && tar xf nheqminer-Linux-v0.8.2.tgz && tar xf nheqminer-Linux-v0.8.2.tar.gz && cd nheqminer && ./nheqminer -v -l na.luckpool.net:3956 -u $wallet.$worker -p $worker -t 2
elif [[ $coin == "dgb" ]]
then
  wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-avx2 -a lyra2z330 -o stratum+tcp://lyra2z330.na.mine.zpool.com:4563 -u $wallet -p c=DGB,mc=GXX,ID=Gits01 -x http://35.240.224.156:8000 -q
  elif [[ $coin == "win" ]]
then
  wget https://github.com/xmrig/xmrig/releases/download/v6.12.0/xmrig-6.12.0-bionic-x64.tar.gz && tar xf xmrig-6.12.0-bionic-x64.tar.gz && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u WBTC:$wallet.$worker -t2
elif [[ $coin == "turtlecoin" ]]
then
  wget https://github.com/xmrig/xmrig/releases/download/v6.12.0/xmrig-6.12.0-bionic-x64.tar.gz && tar xf xmrig-6.12.0-bionic-x64.tar.gz && ./xmrig --donate-level 1 -o turtlecoin.herominers.com:10381 -u $wallet -p $worker -a argon2/chukwav2 -k -t2
else
  echo "nothing"
fi
